<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.lbwxxc.ai</groupId>
        <artifactId>data-visualizer</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>data-visualizer-infrastructure</artifactId>

    <dependencies>
<!--        <dependency>-->
<!--            <groupId>org.mybatis.spring.boot</groupId>-->
<!--            <artifactId>mybatis-spring-boot-starter</artifactId>-->
<!--        </dependency>-->

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- 系统模块 -->
        <dependency>
            <groupId>top.lbwxxc.ai</groupId>
            <artifactId>data-visualizer-domain</artifactId>
        </dependency>
        <!-- 引入 netty 做 socket 通信处理 -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>ai-agent-scaffold-lite-infrastructure</finalName>
    </build>

</project>
